// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: patrol.proto

package patrolpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PatrolService_RegisterNewPatrol_FullMethodName    = "/patrolbroker.PatrolService/RegisterNewPatrol"
	PatrolService_GetAllPatrolInfo_FullMethodName     = "/patrolbroker.PatrolService/GetAllPatrolInfo"
	PatrolService_UpdatePatrolLocation_FullMethodName = "/patrolbroker.PatrolService/UpdatePatrolLocation"
	PatrolService_AssignPatrolToCrime_FullMethodName  = "/patrolbroker.PatrolService/AssignPatrolToCrime"
	PatrolService_UpdatePatrolStatus_FullMethodName   = "/patrolbroker.PatrolService/UpdatePatrolStatus"
	PatrolService_PutPatrolInfo_FullMethodName        = "/patrolbroker.PatrolService/PutPatrolInfo"
	PatrolService_PatchPatrolInfo_FullMethodName      = "/patrolbroker.PatrolService/PatchPatrolInfo"
)

// PatrolServiceClient is the client API for PatrolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PatrolServiceClient interface {
	RegisterNewPatrol(ctx context.Context, in *Patrol, opts ...grpc.CallOption) (*NewPatrolRegisterResponse, error)
	GetAllPatrolInfo(ctx context.Context, in *GetPatrolInfoRequest, opts ...grpc.CallOption) (*GetPatrolInfoResponse, error)
	UpdatePatrolLocation(ctx context.Context, in *UpdatePatrolLocationRequest, opts ...grpc.CallOption) (*UpdatePatrolLocationResponse, error)
	AssignPatrolToCrime(ctx context.Context, in *AssignPatrolToCrimeRequest, opts ...grpc.CallOption) (*AssignPatrolToCrimeResponse, error)
	UpdatePatrolStatus(ctx context.Context, in *UpdatePatrolStatusRequest, opts ...grpc.CallOption) (*UpdatePatrolStatusResponse, error)
	PutPatrolInfo(ctx context.Context, in *UpdatePatrolInfoRequest, opts ...grpc.CallOption) (*UpdatePatrolInfoResponse, error)
	PatchPatrolInfo(ctx context.Context, in *UpdatePatrolInfoRequest, opts ...grpc.CallOption) (*UpdatePatrolInfoResponse, error)
}

type patrolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPatrolServiceClient(cc grpc.ClientConnInterface) PatrolServiceClient {
	return &patrolServiceClient{cc}
}

func (c *patrolServiceClient) RegisterNewPatrol(ctx context.Context, in *Patrol, opts ...grpc.CallOption) (*NewPatrolRegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewPatrolRegisterResponse)
	err := c.cc.Invoke(ctx, PatrolService_RegisterNewPatrol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patrolServiceClient) GetAllPatrolInfo(ctx context.Context, in *GetPatrolInfoRequest, opts ...grpc.CallOption) (*GetPatrolInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPatrolInfoResponse)
	err := c.cc.Invoke(ctx, PatrolService_GetAllPatrolInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patrolServiceClient) UpdatePatrolLocation(ctx context.Context, in *UpdatePatrolLocationRequest, opts ...grpc.CallOption) (*UpdatePatrolLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePatrolLocationResponse)
	err := c.cc.Invoke(ctx, PatrolService_UpdatePatrolLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patrolServiceClient) AssignPatrolToCrime(ctx context.Context, in *AssignPatrolToCrimeRequest, opts ...grpc.CallOption) (*AssignPatrolToCrimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignPatrolToCrimeResponse)
	err := c.cc.Invoke(ctx, PatrolService_AssignPatrolToCrime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patrolServiceClient) UpdatePatrolStatus(ctx context.Context, in *UpdatePatrolStatusRequest, opts ...grpc.CallOption) (*UpdatePatrolStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePatrolStatusResponse)
	err := c.cc.Invoke(ctx, PatrolService_UpdatePatrolStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patrolServiceClient) PutPatrolInfo(ctx context.Context, in *UpdatePatrolInfoRequest, opts ...grpc.CallOption) (*UpdatePatrolInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePatrolInfoResponse)
	err := c.cc.Invoke(ctx, PatrolService_PutPatrolInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patrolServiceClient) PatchPatrolInfo(ctx context.Context, in *UpdatePatrolInfoRequest, opts ...grpc.CallOption) (*UpdatePatrolInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePatrolInfoResponse)
	err := c.cc.Invoke(ctx, PatrolService_PatchPatrolInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PatrolServiceServer is the server API for PatrolService service.
// All implementations must embed UnimplementedPatrolServiceServer
// for forward compatibility.
type PatrolServiceServer interface {
	RegisterNewPatrol(context.Context, *Patrol) (*NewPatrolRegisterResponse, error)
	GetAllPatrolInfo(context.Context, *GetPatrolInfoRequest) (*GetPatrolInfoResponse, error)
	UpdatePatrolLocation(context.Context, *UpdatePatrolLocationRequest) (*UpdatePatrolLocationResponse, error)
	AssignPatrolToCrime(context.Context, *AssignPatrolToCrimeRequest) (*AssignPatrolToCrimeResponse, error)
	UpdatePatrolStatus(context.Context, *UpdatePatrolStatusRequest) (*UpdatePatrolStatusResponse, error)
	PutPatrolInfo(context.Context, *UpdatePatrolInfoRequest) (*UpdatePatrolInfoResponse, error)
	PatchPatrolInfo(context.Context, *UpdatePatrolInfoRequest) (*UpdatePatrolInfoResponse, error)
	mustEmbedUnimplementedPatrolServiceServer()
}

// UnimplementedPatrolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPatrolServiceServer struct{}

func (UnimplementedPatrolServiceServer) RegisterNewPatrol(context.Context, *Patrol) (*NewPatrolRegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNewPatrol not implemented")
}
func (UnimplementedPatrolServiceServer) GetAllPatrolInfo(context.Context, *GetPatrolInfoRequest) (*GetPatrolInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllPatrolInfo not implemented")
}
func (UnimplementedPatrolServiceServer) UpdatePatrolLocation(context.Context, *UpdatePatrolLocationRequest) (*UpdatePatrolLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePatrolLocation not implemented")
}
func (UnimplementedPatrolServiceServer) AssignPatrolToCrime(context.Context, *AssignPatrolToCrimeRequest) (*AssignPatrolToCrimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignPatrolToCrime not implemented")
}
func (UnimplementedPatrolServiceServer) UpdatePatrolStatus(context.Context, *UpdatePatrolStatusRequest) (*UpdatePatrolStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePatrolStatus not implemented")
}
func (UnimplementedPatrolServiceServer) PutPatrolInfo(context.Context, *UpdatePatrolInfoRequest) (*UpdatePatrolInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutPatrolInfo not implemented")
}
func (UnimplementedPatrolServiceServer) PatchPatrolInfo(context.Context, *UpdatePatrolInfoRequest) (*UpdatePatrolInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchPatrolInfo not implemented")
}
func (UnimplementedPatrolServiceServer) mustEmbedUnimplementedPatrolServiceServer() {}
func (UnimplementedPatrolServiceServer) testEmbeddedByValue()                       {}

// UnsafePatrolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PatrolServiceServer will
// result in compilation errors.
type UnsafePatrolServiceServer interface {
	mustEmbedUnimplementedPatrolServiceServer()
}

func RegisterPatrolServiceServer(s grpc.ServiceRegistrar, srv PatrolServiceServer) {
	// If the following call pancis, it indicates UnimplementedPatrolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PatrolService_ServiceDesc, srv)
}

func _PatrolService_RegisterNewPatrol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Patrol)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatrolServiceServer).RegisterNewPatrol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatrolService_RegisterNewPatrol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatrolServiceServer).RegisterNewPatrol(ctx, req.(*Patrol))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatrolService_GetAllPatrolInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPatrolInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatrolServiceServer).GetAllPatrolInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatrolService_GetAllPatrolInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatrolServiceServer).GetAllPatrolInfo(ctx, req.(*GetPatrolInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatrolService_UpdatePatrolLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePatrolLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatrolServiceServer).UpdatePatrolLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatrolService_UpdatePatrolLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatrolServiceServer).UpdatePatrolLocation(ctx, req.(*UpdatePatrolLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatrolService_AssignPatrolToCrime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignPatrolToCrimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatrolServiceServer).AssignPatrolToCrime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatrolService_AssignPatrolToCrime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatrolServiceServer).AssignPatrolToCrime(ctx, req.(*AssignPatrolToCrimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatrolService_UpdatePatrolStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePatrolStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatrolServiceServer).UpdatePatrolStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatrolService_UpdatePatrolStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatrolServiceServer).UpdatePatrolStatus(ctx, req.(*UpdatePatrolStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatrolService_PutPatrolInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePatrolInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatrolServiceServer).PutPatrolInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatrolService_PutPatrolInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatrolServiceServer).PutPatrolInfo(ctx, req.(*UpdatePatrolInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatrolService_PatchPatrolInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePatrolInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatrolServiceServer).PatchPatrolInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatrolService_PatchPatrolInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatrolServiceServer).PatchPatrolInfo(ctx, req.(*UpdatePatrolInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PatrolService_ServiceDesc is the grpc.ServiceDesc for PatrolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PatrolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "patrolbroker.PatrolService",
	HandlerType: (*PatrolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNewPatrol",
			Handler:    _PatrolService_RegisterNewPatrol_Handler,
		},
		{
			MethodName: "GetAllPatrolInfo",
			Handler:    _PatrolService_GetAllPatrolInfo_Handler,
		},
		{
			MethodName: "UpdatePatrolLocation",
			Handler:    _PatrolService_UpdatePatrolLocation_Handler,
		},
		{
			MethodName: "AssignPatrolToCrime",
			Handler:    _PatrolService_AssignPatrolToCrime_Handler,
		},
		{
			MethodName: "UpdatePatrolStatus",
			Handler:    _PatrolService_UpdatePatrolStatus_Handler,
		},
		{
			MethodName: "PutPatrolInfo",
			Handler:    _PatrolService_PutPatrolInfo_Handler,
		},
		{
			MethodName: "PatchPatrolInfo",
			Handler:    _PatrolService_PatchPatrolInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "patrol.proto",
}
