// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: patrol.proto

package patrolpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PatrolStatus int32

const (
	PatrolStatus_AVAILABLE PatrolStatus = 0
	PatrolStatus_BUSY      PatrolStatus = 1
	PatrolStatus_OFF_DUTY  PatrolStatus = 2
)

// Enum value maps for PatrolStatus.
var (
	PatrolStatus_name = map[int32]string{
		0: "AVAILABLE",
		1: "BUSY",
		2: "OFF_DUTY",
	}
	PatrolStatus_value = map[string]int32{
		"AVAILABLE": 0,
		"BUSY":      1,
		"OFF_DUTY":  2,
	}
)

func (x PatrolStatus) Enum() *PatrolStatus {
	p := new(PatrolStatus)
	*p = x
	return p
}

func (x PatrolStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PatrolStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_patrol_proto_enumTypes[0].Descriptor()
}

func (PatrolStatus) Type() protoreflect.EnumType {
	return &file_patrol_proto_enumTypes[0]
}

func (x PatrolStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PatrolStatus.Descriptor instead.
func (PatrolStatus) EnumDescriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{0}
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_patrol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Location) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Location) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type Patrol struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OfficerId     string                 `protobuf:"bytes,2,opt,name=officer_id,json=officerId,proto3" json:"officer_id,omitempty"`
	OfficerName   string                 `protobuf:"bytes,3,opt,name=officer_name,json=officerName,proto3" json:"officer_name,omitempty"`
	Status        *PatrolStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=patrolbroker.PatrolStatus,oneof" json:"status,omitempty"`
	Location      *Location              `protobuf:"bytes,5,opt,name=location,proto3,oneof" json:"location,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3,oneof" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Patrol) Reset() {
	*x = Patrol{}
	mi := &file_patrol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Patrol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patrol) ProtoMessage() {}

func (x *Patrol) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Patrol.ProtoReflect.Descriptor instead.
func (*Patrol) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{1}
}

func (x *Patrol) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Patrol) GetOfficerId() string {
	if x != nil {
		return x.OfficerId
	}
	return ""
}

func (x *Patrol) GetOfficerName() string {
	if x != nil {
		return x.OfficerName
	}
	return ""
}

func (x *Patrol) GetStatus() PatrolStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return PatrolStatus_AVAILABLE
}

func (x *Patrol) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Patrol) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Patrol) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type NewPatrolRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatrolId      string                 `protobuf:"bytes,1,opt,name=patrol_id,json=patrolId,proto3" json:"patrol_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewPatrolRegisterResponse) Reset() {
	*x = NewPatrolRegisterResponse{}
	mi := &file_patrol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewPatrolRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPatrolRegisterResponse) ProtoMessage() {}

func (x *NewPatrolRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPatrolRegisterResponse.ProtoReflect.Descriptor instead.
func (*NewPatrolRegisterResponse) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{2}
}

func (x *NewPatrolRegisterResponse) GetPatrolId() string {
	if x != nil {
		return x.PatrolId
	}
	return ""
}

func (x *NewPatrolRegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NewPatrolRegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NewStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        PatrolStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=patrolbroker.PatrolStatus" json:"status,omitempty"`
	Location      *Location              `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewStatus) Reset() {
	*x = NewStatus{}
	mi := &file_patrol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewStatus) ProtoMessage() {}

func (x *NewStatus) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewStatus.ProtoReflect.Descriptor instead.
func (*NewStatus) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{3}
}

func (x *NewStatus) GetStatus() PatrolStatus {
	if x != nil {
		return x.Status
	}
	return PatrolStatus_AVAILABLE
}

func (x *NewStatus) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type GetPatrolInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *string                `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	OfficerId     *string                `protobuf:"bytes,2,opt,name=officer_id,json=officerId,proto3,oneof" json:"officer_id,omitempty"`
	OfficerName   *string                `protobuf:"bytes,3,opt,name=officer_name,json=officerName,proto3,oneof" json:"officer_name,omitempty"`
	Status        *PatrolStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=patrolbroker.PatrolStatus,oneof" json:"status,omitempty"`
	Street        *string                `protobuf:"bytes,5,opt,name=street,proto3,oneof" json:"street,omitempty"`
	City          *string                `protobuf:"bytes,6,opt,name=city,proto3,oneof" json:"city,omitempty"`
	State         *string                `protobuf:"bytes,7,opt,name=state,proto3,oneof" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatrolInfoRequest) Reset() {
	*x = GetPatrolInfoRequest{}
	mi := &file_patrol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatrolInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatrolInfoRequest) ProtoMessage() {}

func (x *GetPatrolInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatrolInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPatrolInfoRequest) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{4}
}

func (x *GetPatrolInfoRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *GetPatrolInfoRequest) GetOfficerId() string {
	if x != nil && x.OfficerId != nil {
		return *x.OfficerId
	}
	return ""
}

func (x *GetPatrolInfoRequest) GetOfficerName() string {
	if x != nil && x.OfficerName != nil {
		return *x.OfficerName
	}
	return ""
}

func (x *GetPatrolInfoRequest) GetStatus() PatrolStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return PatrolStatus_AVAILABLE
}

func (x *GetPatrolInfoRequest) GetStreet() string {
	if x != nil && x.Street != nil {
		return *x.Street
	}
	return ""
}

func (x *GetPatrolInfoRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *GetPatrolInfoRequest) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

type GetPatrolInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patrols       []*Patrol              `protobuf:"bytes,1,rep,name=patrols,proto3" json:"patrols,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatrolInfoResponse) Reset() {
	*x = GetPatrolInfoResponse{}
	mi := &file_patrol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatrolInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatrolInfoResponse) ProtoMessage() {}

func (x *GetPatrolInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatrolInfoResponse.ProtoReflect.Descriptor instead.
func (*GetPatrolInfoResponse) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{5}
}

func (x *GetPatrolInfoResponse) GetPatrols() []*Patrol {
	if x != nil {
		return x.Patrols
	}
	return nil
}

func (x *GetPatrolInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPatrolInfoResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type UpdatePatrolLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Location      *Location              `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePatrolLocationRequest) Reset() {
	*x = UpdatePatrolLocationRequest{}
	mi := &file_patrol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePatrolLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePatrolLocationRequest) ProtoMessage() {}

func (x *UpdatePatrolLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePatrolLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdatePatrolLocationRequest) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePatrolLocationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePatrolLocationRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type UpdatePatrolLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePatrolLocationResponse) Reset() {
	*x = UpdatePatrolLocationResponse{}
	mi := &file_patrol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePatrolLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePatrolLocationResponse) ProtoMessage() {}

func (x *UpdatePatrolLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePatrolLocationResponse.ProtoReflect.Descriptor instead.
func (*UpdatePatrolLocationResponse) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePatrolLocationResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePatrolLocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AssignPatrolToCrimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatrolId      string                 `protobuf:"bytes,1,opt,name=patrol_id,json=patrolId,proto3" json:"patrol_id,omitempty"`
	CrimeId       string                 `protobuf:"bytes,2,opt,name=crime_id,json=crimeId,proto3" json:"crime_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPatrolToCrimeRequest) Reset() {
	*x = AssignPatrolToCrimeRequest{}
	mi := &file_patrol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPatrolToCrimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPatrolToCrimeRequest) ProtoMessage() {}

func (x *AssignPatrolToCrimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPatrolToCrimeRequest.ProtoReflect.Descriptor instead.
func (*AssignPatrolToCrimeRequest) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{8}
}

func (x *AssignPatrolToCrimeRequest) GetPatrolId() string {
	if x != nil {
		return x.PatrolId
	}
	return ""
}

func (x *AssignPatrolToCrimeRequest) GetCrimeId() string {
	if x != nil {
		return x.CrimeId
	}
	return ""
}

type AssignPatrolToCrimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatrolId      string                 `protobuf:"bytes,1,opt,name=patrol_id,json=patrolId,proto3" json:"patrol_id,omitempty"`
	CrimeId       string                 `protobuf:"bytes,2,opt,name=crime_id,json=crimeId,proto3" json:"crime_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,4,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPatrolToCrimeResponse) Reset() {
	*x = AssignPatrolToCrimeResponse{}
	mi := &file_patrol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPatrolToCrimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPatrolToCrimeResponse) ProtoMessage() {}

func (x *AssignPatrolToCrimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPatrolToCrimeResponse.ProtoReflect.Descriptor instead.
func (*AssignPatrolToCrimeResponse) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{9}
}

func (x *AssignPatrolToCrimeResponse) GetPatrolId() string {
	if x != nil {
		return x.PatrolId
	}
	return ""
}

func (x *AssignPatrolToCrimeResponse) GetCrimeId() string {
	if x != nil {
		return x.CrimeId
	}
	return ""
}

func (x *AssignPatrolToCrimeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AssignPatrolToCrimeResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type UpdatePatrolStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatrolId      string                 `protobuf:"bytes,1,opt,name=patrol_id,json=patrolId,proto3" json:"patrol_id,omitempty"`
	Status        PatrolStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=patrolbroker.PatrolStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePatrolStatusRequest) Reset() {
	*x = UpdatePatrolStatusRequest{}
	mi := &file_patrol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePatrolStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePatrolStatusRequest) ProtoMessage() {}

func (x *UpdatePatrolStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePatrolStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdatePatrolStatusRequest) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePatrolStatusRequest) GetPatrolId() string {
	if x != nil {
		return x.PatrolId
	}
	return ""
}

func (x *UpdatePatrolStatusRequest) GetStatus() PatrolStatus {
	if x != nil {
		return x.Status
	}
	return PatrolStatus_AVAILABLE
}

type UpdatePatrolStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatrolId      string                 `protobuf:"bytes,1,opt,name=patrol_id,json=patrolId,proto3" json:"patrol_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePatrolStatusResponse) Reset() {
	*x = UpdatePatrolStatusResponse{}
	mi := &file_patrol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePatrolStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePatrolStatusResponse) ProtoMessage() {}

func (x *UpdatePatrolStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePatrolStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdatePatrolStatusResponse) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{11}
}

func (x *UpdatePatrolStatusResponse) GetPatrolId() string {
	if x != nil {
		return x.PatrolId
	}
	return ""
}

func (x *UpdatePatrolStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdatePatrolStatusResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type GetOnePatrolInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatrolId      string                 `protobuf:"bytes,1,opt,name=patrol_id,json=patrolId,proto3" json:"patrol_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnePatrolInfoRequest) Reset() {
	*x = GetOnePatrolInfoRequest{}
	mi := &file_patrol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnePatrolInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnePatrolInfoRequest) ProtoMessage() {}

func (x *GetOnePatrolInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnePatrolInfoRequest.ProtoReflect.Descriptor instead.
func (*GetOnePatrolInfoRequest) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{12}
}

func (x *GetOnePatrolInfoRequest) GetPatrolId() string {
	if x != nil {
		return x.PatrolId
	}
	return ""
}

type GetOnePatrolInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patrol        *Patrol                `protobuf:"bytes,1,opt,name=patrol,proto3" json:"patrol,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnePatrolInfoResponse) Reset() {
	*x = GetOnePatrolInfoResponse{}
	mi := &file_patrol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnePatrolInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnePatrolInfoResponse) ProtoMessage() {}

func (x *GetOnePatrolInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnePatrolInfoResponse.ProtoReflect.Descriptor instead.
func (*GetOnePatrolInfoResponse) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{13}
}

func (x *GetOnePatrolInfoResponse) GetPatrol() *Patrol {
	if x != nil {
		return x.Patrol
	}
	return nil
}

func (x *GetOnePatrolInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetOnePatrolInfoResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type UpdatePatrolInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OfficerId     *string                `protobuf:"bytes,2,opt,name=officer_id,json=officerId,proto3,oneof" json:"officer_id,omitempty"`
	OfficerName   *string                `protobuf:"bytes,3,opt,name=officer_name,json=officerName,proto3,oneof" json:"officer_name,omitempty"`
	Status        *PatrolStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=patrolbroker.PatrolStatus,oneof" json:"status,omitempty"`
	Street        *string                `protobuf:"bytes,5,opt,name=street,proto3,oneof" json:"street,omitempty"`
	City          *string                `protobuf:"bytes,6,opt,name=city,proto3,oneof" json:"city,omitempty"`
	State         *string                `protobuf:"bytes,7,opt,name=state,proto3,oneof" json:"state,omitempty"`
	Latitude      *float64               `protobuf:"fixed64,8,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude     *float64               `protobuf:"fixed64,9,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePatrolInfoRequest) Reset() {
	*x = UpdatePatrolInfoRequest{}
	mi := &file_patrol_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePatrolInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePatrolInfoRequest) ProtoMessage() {}

func (x *UpdatePatrolInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePatrolInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdatePatrolInfoRequest) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{14}
}

func (x *UpdatePatrolInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePatrolInfoRequest) GetOfficerId() string {
	if x != nil && x.OfficerId != nil {
		return *x.OfficerId
	}
	return ""
}

func (x *UpdatePatrolInfoRequest) GetOfficerName() string {
	if x != nil && x.OfficerName != nil {
		return *x.OfficerName
	}
	return ""
}

func (x *UpdatePatrolInfoRequest) GetStatus() PatrolStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return PatrolStatus_AVAILABLE
}

func (x *UpdatePatrolInfoRequest) GetStreet() string {
	if x != nil && x.Street != nil {
		return *x.Street
	}
	return ""
}

func (x *UpdatePatrolInfoRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *UpdatePatrolInfoRequest) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *UpdatePatrolInfoRequest) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *UpdatePatrolInfoRequest) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

type UpdatePatrolInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatrolId      string                 `protobuf:"bytes,1,opt,name=patrol_id,json=patrolId,proto3" json:"patrol_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       *string                `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePatrolInfoResponse) Reset() {
	*x = UpdatePatrolInfoResponse{}
	mi := &file_patrol_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePatrolInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePatrolInfoResponse) ProtoMessage() {}

func (x *UpdatePatrolInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patrol_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePatrolInfoResponse.ProtoReflect.Descriptor instead.
func (*UpdatePatrolInfoResponse) Descriptor() ([]byte, []int) {
	return file_patrol_proto_rawDescGZIP(), []int{15}
}

func (x *UpdatePatrolInfoResponse) GetPatrolId() string {
	if x != nil {
		return x.PatrolId
	}
	return ""
}

func (x *UpdatePatrolInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdatePatrolInfoResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_patrol_proto protoreflect.FileDescriptor

const file_patrol_proto_rawDesc = "" +
	"\n" +
	"\fpatrol.proto\x12\fpatrolbroker\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x01\n" +
	"\bLocation\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\"\x8b\x03\n" +
	"\x06Patrol\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"officer_id\x18\x02 \x01(\tR\tofficerId\x12!\n" +
	"\fofficer_name\x18\x03 \x01(\tR\vofficerName\x127\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1a.patrolbroker.PatrolStatusH\x00R\x06status\x88\x01\x01\x127\n" +
	"\blocation\x18\x05 \x01(\v2\x16.patrolbroker.LocationH\x01R\blocation\x88\x01\x01\x12>\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\tcreatedAt\x88\x01\x01\x12>\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x03R\tupdatedAt\x88\x01\x01B\t\n" +
	"\a_statusB\v\n" +
	"\t_locationB\r\n" +
	"\v_created_atB\r\n" +
	"\v_updated_at\"l\n" +
	"\x19NewPatrolRegisterResponse\x12\x1b\n" +
	"\tpatrol_id\x18\x01 \x01(\tR\bpatrolId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"s\n" +
	"\tNewStatus\x122\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1a.patrolbroker.PatrolStatusR\x06status\x122\n" +
	"\blocation\x18\x02 \x01(\v2\x16.patrolbroker.LocationR\blocation\"\xdf\x02\n" +
	"\x14GetPatrolInfoRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\tH\x00R\x06userId\x88\x01\x01\x12\"\n" +
	"\n" +
	"officer_id\x18\x02 \x01(\tH\x01R\tofficerId\x88\x01\x01\x12&\n" +
	"\fofficer_name\x18\x03 \x01(\tH\x02R\vofficerName\x88\x01\x01\x127\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1a.patrolbroker.PatrolStatusH\x03R\x06status\x88\x01\x01\x12\x1b\n" +
	"\x06street\x18\x05 \x01(\tH\x04R\x06street\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x06 \x01(\tH\x05R\x04city\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\a \x01(\tH\x06R\x05state\x88\x01\x01B\n" +
	"\n" +
	"\b_user_idB\r\n" +
	"\v_officer_idB\x0f\n" +
	"\r_officer_nameB\t\n" +
	"\a_statusB\t\n" +
	"\a_streetB\a\n" +
	"\x05_cityB\b\n" +
	"\x06_state\"\x8c\x01\n" +
	"\x15GetPatrolInfoResponse\x12.\n" +
	"\apatrols\x18\x01 \x03(\v2\x14.patrolbroker.PatrolR\apatrols\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"j\n" +
	"\x1bUpdatePatrolLocationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x122\n" +
	"\blocation\x18\x02 \x01(\v2\x16.patrolbroker.LocationR\blocation\"Q\n" +
	"\x1cUpdatePatrolLocationResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"T\n" +
	"\x1aAssignPatrolToCrimeRequest\x12\x1b\n" +
	"\tpatrol_id\x18\x01 \x01(\tR\bpatrolId\x12\x19\n" +
	"\bcrime_id\x18\x02 \x01(\tR\acrimeId\"\x9a\x01\n" +
	"\x1bAssignPatrolToCrimeResponse\x12\x1b\n" +
	"\tpatrol_id\x18\x01 \x01(\tR\bpatrolId\x12\x19\n" +
	"\bcrime_id\x18\x02 \x01(\tR\acrimeId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1d\n" +
	"\amessage\x18\x04 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"l\n" +
	"\x19UpdatePatrolStatusRequest\x12\x1b\n" +
	"\tpatrol_id\x18\x01 \x01(\tR\bpatrolId\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.patrolbroker.PatrolStatusR\x06status\"~\n" +
	"\x1aUpdatePatrolStatusResponse\x12\x1b\n" +
	"\tpatrol_id\x18\x01 \x01(\tR\bpatrolId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"6\n" +
	"\x17GetOnePatrolInfoRequest\x12\x1b\n" +
	"\tpatrol_id\x18\x01 \x01(\tR\bpatrolId\"\x8d\x01\n" +
	"\x18GetOnePatrolInfoResponse\x12,\n" +
	"\x06patrol\x18\x01 \x01(\v2\x14.patrolbroker.PatrolR\x06patrol\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"\xb0\x03\n" +
	"\x17UpdatePatrolInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\"\n" +
	"\n" +
	"officer_id\x18\x02 \x01(\tH\x00R\tofficerId\x88\x01\x01\x12&\n" +
	"\fofficer_name\x18\x03 \x01(\tH\x01R\vofficerName\x88\x01\x01\x127\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1a.patrolbroker.PatrolStatusH\x02R\x06status\x88\x01\x01\x12\x1b\n" +
	"\x06street\x18\x05 \x01(\tH\x03R\x06street\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x06 \x01(\tH\x04R\x04city\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\a \x01(\tH\x05R\x05state\x88\x01\x01\x12\x1f\n" +
	"\blatitude\x18\b \x01(\x01H\x06R\blatitude\x88\x01\x01\x12!\n" +
	"\tlongitude\x18\t \x01(\x01H\aR\tlongitude\x88\x01\x01B\r\n" +
	"\v_officer_idB\x0f\n" +
	"\r_officer_nameB\t\n" +
	"\a_statusB\t\n" +
	"\a_streetB\a\n" +
	"\x05_cityB\b\n" +
	"\x06_stateB\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitude\"|\n" +
	"\x18UpdatePatrolInfoResponse\x12\x1b\n" +
	"\tpatrol_id\x18\x01 \x01(\tR\bpatrolId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message*5\n" +
	"\fPatrolStatus\x12\r\n" +
	"\tAVAILABLE\x10\x00\x12\b\n" +
	"\x04BUSY\x10\x01\x12\f\n" +
	"\bOFF_DUTY\x10\x022\xc6\x05\n" +
	"\rPatrolService\x12R\n" +
	"\x11RegisterNewPatrol\x12\x14.patrolbroker.Patrol\x1a'.patrolbroker.NewPatrolRegisterResponse\x12[\n" +
	"\x10GetAllPatrolInfo\x12\".patrolbroker.GetPatrolInfoRequest\x1a#.patrolbroker.GetPatrolInfoResponse\x12m\n" +
	"\x14UpdatePatrolLocation\x12).patrolbroker.UpdatePatrolLocationRequest\x1a*.patrolbroker.UpdatePatrolLocationResponse\x12j\n" +
	"\x13AssignPatrolToCrime\x12(.patrolbroker.AssignPatrolToCrimeRequest\x1a).patrolbroker.AssignPatrolToCrimeResponse\x12g\n" +
	"\x12UpdatePatrolStatus\x12'.patrolbroker.UpdatePatrolStatusRequest\x1a(.patrolbroker.UpdatePatrolStatusResponse\x12^\n" +
	"\rPutPatrolInfo\x12%.patrolbroker.UpdatePatrolInfoRequest\x1a&.patrolbroker.UpdatePatrolInfoResponse\x12`\n" +
	"\x0fPatchPatrolInfo\x12%.patrolbroker.UpdatePatrolInfoRequest\x1a&.patrolbroker.UpdatePatrolInfoResponseB\x15Z\x13./patrolpb;patrolpbb\x06proto3"

var (
	file_patrol_proto_rawDescOnce sync.Once
	file_patrol_proto_rawDescData []byte
)

func file_patrol_proto_rawDescGZIP() []byte {
	file_patrol_proto_rawDescOnce.Do(func() {
		file_patrol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_patrol_proto_rawDesc), len(file_patrol_proto_rawDesc)))
	})
	return file_patrol_proto_rawDescData
}

var file_patrol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_patrol_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_patrol_proto_goTypes = []any{
	(PatrolStatus)(0),                    // 0: patrolbroker.PatrolStatus
	(*Location)(nil),                     // 1: patrolbroker.Location
	(*Patrol)(nil),                       // 2: patrolbroker.Patrol
	(*NewPatrolRegisterResponse)(nil),    // 3: patrolbroker.NewPatrolRegisterResponse
	(*NewStatus)(nil),                    // 4: patrolbroker.NewStatus
	(*GetPatrolInfoRequest)(nil),         // 5: patrolbroker.GetPatrolInfoRequest
	(*GetPatrolInfoResponse)(nil),        // 6: patrolbroker.GetPatrolInfoResponse
	(*UpdatePatrolLocationRequest)(nil),  // 7: patrolbroker.UpdatePatrolLocationRequest
	(*UpdatePatrolLocationResponse)(nil), // 8: patrolbroker.UpdatePatrolLocationResponse
	(*AssignPatrolToCrimeRequest)(nil),   // 9: patrolbroker.AssignPatrolToCrimeRequest
	(*AssignPatrolToCrimeResponse)(nil),  // 10: patrolbroker.AssignPatrolToCrimeResponse
	(*UpdatePatrolStatusRequest)(nil),    // 11: patrolbroker.UpdatePatrolStatusRequest
	(*UpdatePatrolStatusResponse)(nil),   // 12: patrolbroker.UpdatePatrolStatusResponse
	(*GetOnePatrolInfoRequest)(nil),      // 13: patrolbroker.GetOnePatrolInfoRequest
	(*GetOnePatrolInfoResponse)(nil),     // 14: patrolbroker.GetOnePatrolInfoResponse
	(*UpdatePatrolInfoRequest)(nil),      // 15: patrolbroker.UpdatePatrolInfoRequest
	(*UpdatePatrolInfoResponse)(nil),     // 16: patrolbroker.UpdatePatrolInfoResponse
	(*timestamppb.Timestamp)(nil),        // 17: google.protobuf.Timestamp
}
var file_patrol_proto_depIdxs = []int32{
	0,  // 0: patrolbroker.Patrol.status:type_name -> patrolbroker.PatrolStatus
	1,  // 1: patrolbroker.Patrol.location:type_name -> patrolbroker.Location
	17, // 2: patrolbroker.Patrol.created_at:type_name -> google.protobuf.Timestamp
	17, // 3: patrolbroker.Patrol.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: patrolbroker.NewStatus.status:type_name -> patrolbroker.PatrolStatus
	1,  // 5: patrolbroker.NewStatus.location:type_name -> patrolbroker.Location
	0,  // 6: patrolbroker.GetPatrolInfoRequest.status:type_name -> patrolbroker.PatrolStatus
	2,  // 7: patrolbroker.GetPatrolInfoResponse.patrols:type_name -> patrolbroker.Patrol
	1,  // 8: patrolbroker.UpdatePatrolLocationRequest.location:type_name -> patrolbroker.Location
	0,  // 9: patrolbroker.UpdatePatrolStatusRequest.status:type_name -> patrolbroker.PatrolStatus
	2,  // 10: patrolbroker.GetOnePatrolInfoResponse.patrol:type_name -> patrolbroker.Patrol
	0,  // 11: patrolbroker.UpdatePatrolInfoRequest.status:type_name -> patrolbroker.PatrolStatus
	2,  // 12: patrolbroker.PatrolService.RegisterNewPatrol:input_type -> patrolbroker.Patrol
	5,  // 13: patrolbroker.PatrolService.GetAllPatrolInfo:input_type -> patrolbroker.GetPatrolInfoRequest
	7,  // 14: patrolbroker.PatrolService.UpdatePatrolLocation:input_type -> patrolbroker.UpdatePatrolLocationRequest
	9,  // 15: patrolbroker.PatrolService.AssignPatrolToCrime:input_type -> patrolbroker.AssignPatrolToCrimeRequest
	11, // 16: patrolbroker.PatrolService.UpdatePatrolStatus:input_type -> patrolbroker.UpdatePatrolStatusRequest
	15, // 17: patrolbroker.PatrolService.PutPatrolInfo:input_type -> patrolbroker.UpdatePatrolInfoRequest
	15, // 18: patrolbroker.PatrolService.PatchPatrolInfo:input_type -> patrolbroker.UpdatePatrolInfoRequest
	3,  // 19: patrolbroker.PatrolService.RegisterNewPatrol:output_type -> patrolbroker.NewPatrolRegisterResponse
	6,  // 20: patrolbroker.PatrolService.GetAllPatrolInfo:output_type -> patrolbroker.GetPatrolInfoResponse
	8,  // 21: patrolbroker.PatrolService.UpdatePatrolLocation:output_type -> patrolbroker.UpdatePatrolLocationResponse
	10, // 22: patrolbroker.PatrolService.AssignPatrolToCrime:output_type -> patrolbroker.AssignPatrolToCrimeResponse
	12, // 23: patrolbroker.PatrolService.UpdatePatrolStatus:output_type -> patrolbroker.UpdatePatrolStatusResponse
	16, // 24: patrolbroker.PatrolService.PutPatrolInfo:output_type -> patrolbroker.UpdatePatrolInfoResponse
	16, // 25: patrolbroker.PatrolService.PatchPatrolInfo:output_type -> patrolbroker.UpdatePatrolInfoResponse
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_patrol_proto_init() }
func file_patrol_proto_init() {
	if File_patrol_proto != nil {
		return
	}
	file_patrol_proto_msgTypes[1].OneofWrappers = []any{}
	file_patrol_proto_msgTypes[4].OneofWrappers = []any{}
	file_patrol_proto_msgTypes[5].OneofWrappers = []any{}
	file_patrol_proto_msgTypes[9].OneofWrappers = []any{}
	file_patrol_proto_msgTypes[11].OneofWrappers = []any{}
	file_patrol_proto_msgTypes[13].OneofWrappers = []any{}
	file_patrol_proto_msgTypes[14].OneofWrappers = []any{}
	file_patrol_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_patrol_proto_rawDesc), len(file_patrol_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_patrol_proto_goTypes,
		DependencyIndexes: file_patrol_proto_depIdxs,
		EnumInfos:         file_patrol_proto_enumTypes,
		MessageInfos:      file_patrol_proto_msgTypes,
	}.Build()
	File_patrol_proto = out.File
	file_patrol_proto_goTypes = nil
	file_patrol_proto_depIdxs = nil
}
