version: '3'

services:
  postgres:
    image: 'postgres:16'
    ports:
      - "5435:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
  
  crime-service:
    build:
      context: ./../crime-service
      dockerfile: ./../crime-service/crime-service.dockerfile
    restart: always
    ports:
      - "50001:50001"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: ${DSN_TEMPLATE}

  auth-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/auth-service.dockerfile
    restart: always
    ports:
      - "50000:50000"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: ${DSN_TEMPLATE}

  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      SECRET: "this is a very secret key - james" 
    deploy:
      mode: replicated
      replicas: 1
    