version: '3'

services:

  caddy:
    build:
      context: ./../caddy
      dockerfile: ./../caddy/caddy.dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"

  front-end:
    build:
      context: ./../front-end
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ../project-settings/.env
      - ../project-settings/.env.local
    environment:
      # fallback if not defined in env file
      BROKER_SERVICE_URL: ${BROKER_SERVICE_URL:-http://broker-service:8080}

  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      SECRET: ${SECRET}
    deploy:
      mode: replicated
      replicas: 1
  
  crime-service:
    build:
      context: ./../crime-service
      dockerfile: ./../crime-service/crime-service.dockerfile
    restart: always
    ports:
      - "50001:50001"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: ${DSN_TEMPLATE}

  auth-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/auth-service.dockerfile
    restart: always
    ports:
      - "50000:50000"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: ${DSN_TEMPLATE}
      SECRET: ${SECRET}
  
  patrol-service:
    build:
      context: ./../patrol-service
      dockerfile: ./../patrol-service/patrol-service.dockerfile
    restart: always
    ports:
      - "50002:50002"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: ${DSN_TEMPLATE}

  postgres:
    image: 'postgres:16'
    ports:
      - "5435:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
  
  redis:
    image: 'redis:8.0.3-alpine'
    ports:
      - "6379:6379"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
  