version: '3'

services:
  caddy:
    image: jamesguan777/micro-caddy-production:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./../caddy/caddy_data:/data
      - ./../caddy/caddy_config:/config


  front-end:
    image: jamesguan777/crime-front-end:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ../project-settings/.env


  broker-service:
    image: jamesguan777/crime-broker-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ../project-settings/.env


  crime-service:
    image: jamesguan777/crime-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ../project-settings/.env

  auth-service:
    image: jamesguan777/crime-auth-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ../project-settings/.env


  patrol-service:
    image: jamesguan777/crime-patrol-service:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ../project-settings/.env

  postgres:
    image: 'postgres:16'
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ../project-settings/.env
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
      - ./init-scripts:/docker-entrypoint-initdb.d
  
  redis:
    image: 'redis:8.0.3-alpine'
    deploy:
      mode: replicated
      replicas: 1
  
  
volumes:
  caddy_data: 
    external: true
  caddy_config: