// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: crime.proto

package crimepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CrimeStatus int32

const (
	CrimeStatus_NEW      CrimeStatus = 0
	CrimeStatus_ASSIGNED CrimeStatus = 1
	CrimeStatus_RESOLVED CrimeStatus = 2
)

// Enum value maps for CrimeStatus.
var (
	CrimeStatus_name = map[int32]string{
		0: "NEW",
		1: "ASSIGNED",
		2: "RESOLVED",
	}
	CrimeStatus_value = map[string]int32{
		"NEW":      0,
		"ASSIGNED": 1,
		"RESOLVED": 2,
	}
)

func (x CrimeStatus) Enum() *CrimeStatus {
	p := new(CrimeStatus)
	*p = x
	return p
}

func (x CrimeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CrimeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_crime_proto_enumTypes[0].Descriptor()
}

func (CrimeStatus) Type() protoreflect.EnumType {
	return &file_crime_proto_enumTypes[0]
}

func (x CrimeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CrimeStatus.Descriptor instead.
func (CrimeStatus) EnumDescriptor() ([]byte, []int) {
	return file_crime_proto_rawDescGZIP(), []int{0}
}

type PatrolStatus int32

const (
	PatrolStatus_AVAILABLE PatrolStatus = 0
	PatrolStatus_BUSY      PatrolStatus = 1
)

// Enum value maps for PatrolStatus.
var (
	PatrolStatus_name = map[int32]string{
		0: "AVAILABLE",
		1: "BUSY",
	}
	PatrolStatus_value = map[string]int32{
		"AVAILABLE": 0,
		"BUSY":      1,
	}
)

func (x PatrolStatus) Enum() *PatrolStatus {
	p := new(PatrolStatus)
	*p = x
	return p
}

func (x PatrolStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PatrolStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_crime_proto_enumTypes[1].Descriptor()
}

func (PatrolStatus) Type() protoreflect.EnumType {
	return &file_crime_proto_enumTypes[1]
}

func (x PatrolStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PatrolStatus.Descriptor instead.
func (PatrolStatus) EnumDescriptor() ([]byte, []int) {
	return file_crime_proto_rawDescGZIP(), []int{1}
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_crime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_crime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_crime_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Location) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Location) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type Crime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReporterId    string                 `protobuf:"bytes,2,opt,name=reporter_id,json=reporterId,proto3" json:"reporter_id,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        CrimeStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=crimebroker.CrimeStatus" json:"status,omitempty"`
	Location      *Location              `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	ReportedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=reported_at,json=reportedAt,proto3" json:"reported_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Crime) Reset() {
	*x = Crime{}
	mi := &file_crime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Crime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Crime) ProtoMessage() {}

func (x *Crime) ProtoReflect() protoreflect.Message {
	mi := &file_crime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Crime.ProtoReflect.Descriptor instead.
func (*Crime) Descriptor() ([]byte, []int) {
	return file_crime_proto_rawDescGZIP(), []int{1}
}

func (x *Crime) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Crime) GetReporterId() string {
	if x != nil {
		return x.ReporterId
	}
	return ""
}

func (x *Crime) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Crime) GetStatus() CrimeStatus {
	if x != nil {
		return x.Status
	}
	return CrimeStatus_NEW
}

func (x *Crime) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Crime) GetReportedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReportedAt
	}
	return nil
}

func (x *Crime) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Crime) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CrimeReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReporterId    string                 `protobuf:"bytes,1,opt,name=reporter_id,json=reporterId,proto3" json:"reporter_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Location      *Location              `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrimeReportRequest) Reset() {
	*x = CrimeReportRequest{}
	mi := &file_crime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrimeReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrimeReportRequest) ProtoMessage() {}

func (x *CrimeReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrimeReportRequest.ProtoReflect.Descriptor instead.
func (*CrimeReportRequest) Descriptor() ([]byte, []int) {
	return file_crime_proto_rawDescGZIP(), []int{2}
}

func (x *CrimeReportRequest) GetReporterId() string {
	if x != nil {
		return x.ReporterId
	}
	return ""
}

func (x *CrimeReportRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CrimeReportRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type UpdateCrimeReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReporterId    string                 `protobuf:"bytes,2,opt,name=reporter_id,json=reporterId,proto3" json:"reporter_id,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Status        *CrimeStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=crimebroker.CrimeStatus,oneof" json:"status,omitempty"`
	Location      *Location              `protobuf:"bytes,5,opt,name=location,proto3,oneof" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCrimeReportRequest) Reset() {
	*x = UpdateCrimeReportRequest{}
	mi := &file_crime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCrimeReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCrimeReportRequest) ProtoMessage() {}

func (x *UpdateCrimeReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCrimeReportRequest.ProtoReflect.Descriptor instead.
func (*UpdateCrimeReportRequest) Descriptor() ([]byte, []int) {
	return file_crime_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCrimeReportRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCrimeReportRequest) GetReporterId() string {
	if x != nil {
		return x.ReporterId
	}
	return ""
}

func (x *UpdateCrimeReportRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateCrimeReportRequest) GetStatus() CrimeStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return CrimeStatus_NEW
}

func (x *UpdateCrimeReportRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type DeleteCrimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCrimeRequest) Reset() {
	*x = DeleteCrimeRequest{}
	mi := &file_crime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCrimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCrimeRequest) ProtoMessage() {}

func (x *DeleteCrimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCrimeRequest.ProtoReflect.Descriptor instead.
func (*DeleteCrimeRequest) Descriptor() ([]byte, []int) {
	return file_crime_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCrimeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCrimesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	ReporterId     *string                `protobuf:"bytes,2,opt,name=reporter_id,json=reporterId,proto3,oneof" json:"reporter_id,omitempty"`
	Street         *string                `protobuf:"bytes,3,opt,name=street,proto3,oneof" json:"street,omitempty"`
	City           *string                `protobuf:"bytes,4,opt,name=city,proto3,oneof" json:"city,omitempty"`
	State          *string                `protobuf:"bytes,5,opt,name=state,proto3,oneof" json:"state,omitempty"`
	Date           *string                `protobuf:"bytes,6,opt,name=date,proto3,oneof" json:"date,omitempty"`
	Status         *CrimeStatus           `protobuf:"varint,7,opt,name=status,proto3,enum=crimebroker.CrimeStatus,oneof" json:"status,omitempty"`
	FilterKeywords []string               `protobuf:"bytes,8,rep,name=filterKeywords,proto3" json:"filterKeywords,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCrimesRequest) Reset() {
	*x = GetCrimesRequest{}
	mi := &file_crime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCrimesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCrimesRequest) ProtoMessage() {}

func (x *GetCrimesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCrimesRequest.ProtoReflect.Descriptor instead.
func (*GetCrimesRequest) Descriptor() ([]byte, []int) {
	return file_crime_proto_rawDescGZIP(), []int{5}
}

func (x *GetCrimesRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *GetCrimesRequest) GetReporterId() string {
	if x != nil && x.ReporterId != nil {
		return *x.ReporterId
	}
	return ""
}

func (x *GetCrimesRequest) GetStreet() string {
	if x != nil && x.Street != nil {
		return *x.Street
	}
	return ""
}

func (x *GetCrimesRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *GetCrimesRequest) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *GetCrimesRequest) GetDate() string {
	if x != nil && x.Date != nil {
		return *x.Date
	}
	return ""
}

func (x *GetCrimesRequest) GetStatus() CrimeStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return CrimeStatus_NEW
}

func (x *GetCrimesRequest) GetFilterKeywords() []string {
	if x != nil {
		return x.FilterKeywords
	}
	return nil
}

type GetCrimesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Crimes        []*Crime               `protobuf:"bytes,1,rep,name=crimes,proto3" json:"crimes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCrimesResponse) Reset() {
	*x = GetCrimesResponse{}
	mi := &file_crime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCrimesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCrimesResponse) ProtoMessage() {}

func (x *GetCrimesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCrimesResponse.ProtoReflect.Descriptor instead.
func (*GetCrimesResponse) Descriptor() ([]byte, []int) {
	return file_crime_proto_rawDescGZIP(), []int{6}
}

func (x *GetCrimesResponse) GetCrimes() []*Crime {
	if x != nil {
		return x.Crimes
	}
	return nil
}

type CrimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Successful    bool                   `protobuf:"varint,2,opt,name=successful,proto3" json:"successful,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrimeResponse) Reset() {
	*x = CrimeResponse{}
	mi := &file_crime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrimeResponse) ProtoMessage() {}

func (x *CrimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrimeResponse.ProtoReflect.Descriptor instead.
func (*CrimeResponse) Descriptor() ([]byte, []int) {
	return file_crime_proto_rawDescGZIP(), []int{7}
}

func (x *CrimeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CrimeResponse) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *CrimeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_crime_proto protoreflect.FileDescriptor

const file_crime_proto_rawDesc = "" +
	"\n" +
	"\vcrime.proto\x12\vcrimebroker\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x01\n" +
	"\bLocation\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\"\xf2\x02\n" +
	"\x05Crime\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vreporter_id\x18\x02 \x01(\tR\n" +
	"reporterId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x120\n" +
	"\x06status\x18\x04 \x01(\x0e2\x18.crimebroker.CrimeStatusR\x06status\x121\n" +
	"\blocation\x18\x05 \x01(\v2\x15.crimebroker.LocationR\blocation\x12;\n" +
	"\vreported_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reportedAt\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8a\x01\n" +
	"\x12CrimeReportRequest\x12\x1f\n" +
	"\vreporter_id\x18\x01 \x01(\tR\n" +
	"reporterId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x121\n" +
	"\blocation\x18\x03 \x01(\v2\x15.crimebroker.LocationR\blocation\"\x89\x02\n" +
	"\x18UpdateCrimeReportRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vreporter_id\x18\x02 \x01(\tR\n" +
	"reporterId\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x125\n" +
	"\x06status\x18\x04 \x01(\x0e2\x18.crimebroker.CrimeStatusH\x01R\x06status\x88\x01\x01\x126\n" +
	"\blocation\x18\x05 \x01(\v2\x15.crimebroker.LocationH\x02R\blocation\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_statusB\v\n" +
	"\t_location\"$\n" +
	"\x12DeleteCrimeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xdf\x02\n" +
	"\x10GetCrimesRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12$\n" +
	"\vreporter_id\x18\x02 \x01(\tH\x01R\n" +
	"reporterId\x88\x01\x01\x12\x1b\n" +
	"\x06street\x18\x03 \x01(\tH\x02R\x06street\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x04 \x01(\tH\x03R\x04city\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\x05 \x01(\tH\x04R\x05state\x88\x01\x01\x12\x17\n" +
	"\x04date\x18\x06 \x01(\tH\x05R\x04date\x88\x01\x01\x125\n" +
	"\x06status\x18\a \x01(\x0e2\x18.crimebroker.CrimeStatusH\x06R\x06status\x88\x01\x01\x12&\n" +
	"\x0efilterKeywords\x18\b \x03(\tR\x0efilterKeywordsB\x05\n" +
	"\x03_idB\x0e\n" +
	"\f_reporter_idB\t\n" +
	"\a_streetB\a\n" +
	"\x05_cityB\b\n" +
	"\x06_stateB\a\n" +
	"\x05_dateB\t\n" +
	"\a_status\"?\n" +
	"\x11GetCrimesResponse\x12*\n" +
	"\x06crimes\x18\x01 \x03(\v2\x12.crimebroker.CrimeR\x06crimes\"Y\n" +
	"\rCrimeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"successful\x18\x02 \x01(\bR\n" +
	"successful\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*2\n" +
	"\vCrimeStatus\x12\a\n" +
	"\x03NEW\x10\x00\x12\f\n" +
	"\bASSIGNED\x10\x01\x12\f\n" +
	"\bRESOLVED\x10\x02*'\n" +
	"\fPatrolStatus\x12\r\n" +
	"\tAVAILABLE\x10\x00\x12\b\n" +
	"\x04BUSY\x10\x012\xd0\x02\n" +
	"\fCrimeService\x12M\n" +
	"\fGetAllCrimes\x12\x1d.crimebroker.GetCrimesRequest\x1a\x1e.crimebroker.GetCrimesResponse\x12S\n" +
	"\x14SubmitNewCrimeReport\x12\x1f.crimebroker.CrimeReportRequest\x1a\x1a.crimebroker.CrimeResponse\x12P\n" +
	"\vUpdateCrime\x12%.crimebroker.UpdateCrimeReportRequest\x1a\x1a.crimebroker.CrimeResponse\x12J\n" +
	"\vDeleteCrime\x12\x1f.crimebroker.DeleteCrimeRequest\x1a\x1a.crimebroker.CrimeResponseB\x13Z\x11./crimepb;crimepbb\x06proto3"

var (
	file_crime_proto_rawDescOnce sync.Once
	file_crime_proto_rawDescData []byte
)

func file_crime_proto_rawDescGZIP() []byte {
	file_crime_proto_rawDescOnce.Do(func() {
		file_crime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crime_proto_rawDesc), len(file_crime_proto_rawDesc)))
	})
	return file_crime_proto_rawDescData
}

var file_crime_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_crime_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_crime_proto_goTypes = []any{
	(CrimeStatus)(0),                 // 0: crimebroker.CrimeStatus
	(PatrolStatus)(0),                // 1: crimebroker.PatrolStatus
	(*Location)(nil),                 // 2: crimebroker.Location
	(*Crime)(nil),                    // 3: crimebroker.Crime
	(*CrimeReportRequest)(nil),       // 4: crimebroker.CrimeReportRequest
	(*UpdateCrimeReportRequest)(nil), // 5: crimebroker.UpdateCrimeReportRequest
	(*DeleteCrimeRequest)(nil),       // 6: crimebroker.DeleteCrimeRequest
	(*GetCrimesRequest)(nil),         // 7: crimebroker.GetCrimesRequest
	(*GetCrimesResponse)(nil),        // 8: crimebroker.GetCrimesResponse
	(*CrimeResponse)(nil),            // 9: crimebroker.CrimeResponse
	(*timestamppb.Timestamp)(nil),    // 10: google.protobuf.Timestamp
}
var file_crime_proto_depIdxs = []int32{
	0,  // 0: crimebroker.Crime.status:type_name -> crimebroker.CrimeStatus
	2,  // 1: crimebroker.Crime.location:type_name -> crimebroker.Location
	10, // 2: crimebroker.Crime.reported_at:type_name -> google.protobuf.Timestamp
	10, // 3: crimebroker.Crime.created_at:type_name -> google.protobuf.Timestamp
	10, // 4: crimebroker.Crime.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 5: crimebroker.CrimeReportRequest.location:type_name -> crimebroker.Location
	0,  // 6: crimebroker.UpdateCrimeReportRequest.status:type_name -> crimebroker.CrimeStatus
	2,  // 7: crimebroker.UpdateCrimeReportRequest.location:type_name -> crimebroker.Location
	0,  // 8: crimebroker.GetCrimesRequest.status:type_name -> crimebroker.CrimeStatus
	3,  // 9: crimebroker.GetCrimesResponse.crimes:type_name -> crimebroker.Crime
	7,  // 10: crimebroker.CrimeService.GetAllCrimes:input_type -> crimebroker.GetCrimesRequest
	4,  // 11: crimebroker.CrimeService.SubmitNewCrimeReport:input_type -> crimebroker.CrimeReportRequest
	5,  // 12: crimebroker.CrimeService.UpdateCrime:input_type -> crimebroker.UpdateCrimeReportRequest
	6,  // 13: crimebroker.CrimeService.DeleteCrime:input_type -> crimebroker.DeleteCrimeRequest
	8,  // 14: crimebroker.CrimeService.GetAllCrimes:output_type -> crimebroker.GetCrimesResponse
	9,  // 15: crimebroker.CrimeService.SubmitNewCrimeReport:output_type -> crimebroker.CrimeResponse
	9,  // 16: crimebroker.CrimeService.UpdateCrime:output_type -> crimebroker.CrimeResponse
	9,  // 17: crimebroker.CrimeService.DeleteCrime:output_type -> crimebroker.CrimeResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_crime_proto_init() }
func file_crime_proto_init() {
	if File_crime_proto != nil {
		return
	}
	file_crime_proto_msgTypes[3].OneofWrappers = []any{}
	file_crime_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crime_proto_rawDesc), len(file_crime_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crime_proto_goTypes,
		DependencyIndexes: file_crime_proto_depIdxs,
		EnumInfos:         file_crime_proto_enumTypes,
		MessageInfos:      file_crime_proto_msgTypes,
	}.Build()
	File_crime_proto = out.File
	file_crime_proto_goTypes = nil
	file_crime_proto_depIdxs = nil
}
